---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.kibana.serviceName }}
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: germainapm-kibana-port
      port: 5601
      protocol: TCP
      targetPort: kibana-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: {{ .Values.spec.kibana.replicas }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        {{if ge ((regexFind "[0-9]{1,}\\.[0-9]{1,}" .Values.germain.build) | float64) 2023.3 }}
        - image: "{{ .Values.spec.kibana.name }}:{{ .Values.spec.elasticSearch.latestTag }}"
        {{ else }}
        - image: "{{ .Values.spec.kibana.name }}:{{ .Values.spec.elasticSearch.legacyTag }}"
        {{ end }}
          imagePullPolicy: {{ .Values.germain.pullPolicy }}
          name: kibana
          resources:
            requests:
              memory: {{ .Values.spec.kibana.memoryRequest }}
              cpu: {{ .Values.spec.kibana.cpuRequest }}
            limits:
              memory: {{ .Values.spec.kibana.memoryLimit }}
              cpu: {{ .Values.spec.kibana.cpuLimit }}
          ports:
            - containerPort: 5601
              name: kibana-port
              protocol: TCP
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://{{ .Values.spec.elasticSearch.serviceName }}:9200"
          - name: XPACK_SECURITY_ENABLED
            value: "false"