{{ if eq .Values.germainDb.Hostname "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.germainDb.clusterServiceName }}
spec:
  clusterIP: None
  selector:
    app: db

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
spec:
  type: LoadBalancer
  selector:
    app: db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: {{ .Values.spec.mysql.replicas }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.ebsStorageClass.name }}
      resources:
        requests:
          storage: {{ .Values.spec.mysql.volumeClaim }}
  serviceName: {{ .Values.germainDb.clusterServiceName }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: "{{ .Values.spec.mysql.name }}:{{ .Values.spec.mysql.tag }}"
          imagePullPolicy: {{ .Values.germain.pullPolicy }}
          name: germainapm-db
          resources:
            requests:
              memory: {{ .Values.spec.mysql.memoryRequest }}
              cpu: {{ .Values.spec.mysql.cpuRequest }}
            limits:
              memory: {{ .Values.spec.mysql.memoryLimit }}
              cpu: {{ .Values.spec.mysql.cpuLimit }}
          ports:
            - containerPort: 3306
              name: db-port
              protocol: TCP
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.germainDbBootstrap.Password }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
{{ else }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.germainDb.clusterServiceName }}
spec:
  type: ExternalName
  externalName: {{ .Values.germainDb.Hostname }}

{{ end }}