---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.hazelcast.serviceName }}
spec:
  clusterIP: None
  selector:
    app: hazelcast
  ports:
    - name: germainapm-hazelcast-port
      port: 5701
      protocol: TCP
      targetPort: hazelcast-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
spec:
  replicas: {{ .Values.spec.hazelcast.replicas }}
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      volumes:
        - name: lib-path
          hostPath:
            path: /opt/hazelcast/lib
      containers:
        - image: "{{ .Values.spec.hazelcast.name }}:{{ .Values.spec.hazelcast.tag }}"
          imagePullPolicy: {{ .Values.germain.pullPolicy }}
          name: hazelcast
          resources:
            requests:
              memory: {{ .Values.spec.hazelcast.memoryRequest }}
              cpu: {{ .Values.spec.hazelcast.cpuRequest }}
            limits:
              memory: {{ .Values.spec.hazelcast.memoryLimit }}
              cpu: {{ .Values.spec.hazelcast.cpuLimit }}
          ports:
            - containerPort: 5701
              name: hazelcast-port
          env:
            - name: HZ_CLUSTERNAME
              value: "germain"
          volumeMounts:
            - name: lib-path
              mountPath: /opt/hazelcast/lib/apm-rtm-model.jar
              subPath: apm-rtm-model.jar
      initContainers:
      - name: get-apm-rtm-model
        image: busybox
        command: ["/bin/sh", "-c", "wget -q {{ .Values.apmRtmModelUrl }} -O /opt/hazelcast/lib/apm-rtm-model.jar"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-path
          mountPath: /opt/hazelcast/lib