---
# Source: germainux/templates/infra/infra-kibana.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: germainapm-kibana-port
      port: 5601
      protocol: TCP
      targetPort: kibana-port
---
# Source: germainux/templates/infra/infra-kibana.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: "kibana:8.8.1"
          imagePullPolicy: Always
          name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 1000m
          ports:
            - containerPort: 5601
              name: kibana-port
              protocol: TCP
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://germainapm-elasticsearch:9200"
          - name: XPACK_SECURITY_ENABLED
            value: "false"
