---
# Source: germainux/templates/germain/germain-services.yaml
# SERVER - INTERNAL ACCESS
apiVersion: v1
kind: Service
metadata:
  name: germainapm-server
spec:
  selector:
    service-type: server
  type: NodePort
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# SERVER - EXTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: server-lb
spec:
  type: LoadBalancer
  selector:
    service-type: server
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# STORAGE - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-storage
spec:
  type: NodePort
  selector:
    service-type: storage
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# RTM - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-rtm
spec:
  type: NodePort
  selector:
    service-type: rtm
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# SESSION - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-session
spec:
  type: NodePort
  selector:
    service-type: session
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# ACTION - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-action
spec:
  type: NodePort
  selector:
    service-type: action
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# AGGREGATION - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-aggregation
spec:
  type: NodePort
  selector:
    service-type: aggregation
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port

# ANALYTICS - INTERNAL ACCESS
---
# Source: germainux/templates/germain/germain-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-analytics
spec:
  type: NodePort
  selector:
    service-type: analytics
  ports:
   - name: service-port
     port: 8080
     protocol: TCP
     targetPort: container-port
