---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-server
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: server
  template:
    metadata:
      labels:
        service-type: server
    spec:
      hostname: germainapm-server
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var/logs
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-server:2022.5"
          imagePullPolicy: Always
          name: germain-server
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
              name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/tomcat8/logs
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# STORAGE
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-storage
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: storage
  template:
    metadata:
      labels:
        service-type: storage
    spec:
      hostname: germainapm-storage
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
        - name: common-properties
          configMap:
            name: common-properties
        - name: license
          configMap:
            name: license-folder
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-storage
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
              name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "storage"
            - name: BOOTSTRAP_ARGS
              value: --upgrade-schema --upgrade-config -f -r
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
            - name: common-properties
              mountPath: /opt/services/config/common.properties
              subPath: configData
            - name: license
              mountPath: /opt/services/install/configuration/custom/
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(echo ruok | nc germainapm-zookeeper 2181; echo)\" != \"imok\" ]]; do sleep 5; done;",
          "while [[ \"$(nc -z -v -w3 http://germainapm-db 3306 | grep -o open 2>&1)\" != \"open\" ]]; do sleep 10; done;",
          "while [[ \"$(wget --server-response http://germainapm-elasticsearch:9200 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;",
          "while [[ \"$(wget --server-response http://germainapm-activemq:8161 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# RTM
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-rtm
spec:

  replicas: 1

  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: rtm
  template:
    metadata:
      labels:
        service-type: rtm
    spec:
      hostname: germainapm-rtm
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-rtm
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
          - containerPort: 8096
            name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "rtm"
            - name: SERVICE_PORT
              value: "8096"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# SESSION
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-session
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: session
  template:
    metadata:
      labels:
        service-type: session
    spec:
      hostname: germainapm-session
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-session
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
              name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "session"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# ANALYTICS
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-analytics
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: analytics
  template:
    metadata:
      labels:
        service-type: analytics
    spec:
      hostname: germainapm-analytics
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-analytics
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
          - containerPort: 8094
            name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "analytics"
            - name: SERVICE_PORT
              value: "8094"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# AGGREGATION
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-aggregation
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: aggregation
  template:
    metadata:
      labels:
        service-type: aggregation
    spec:
      hostname: germainapm-aggregation
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-aggregation
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
          - containerPort: 8092
            name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "aggregation"
            - name: SERVICE_PORT
              value: "8092"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true

# ACTION
---
# Source: germainux/templates/germain/germain.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: germainapm-action
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service-type: action
  template:
    metadata:
      labels:
        service-type: action
    spec:
      hostname: germainapm-action
      volumes:
        - name: var-logs
          hostPath:
            path: /opt/var
      containers:
        - image: "public.ecr.aws/h0m9e4y5/germainapm-services:2022.5"
          imagePullPolicy: Always
          name: germainapm-action
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
              name: container-port
          env:
            - name: GERMAIN_ENV
              value: "germain"
            - name: ZK_URL
              value: "germainapm-zookeeper:2181"
            - name: ELASTIC_URL
              value: "true"
            - name: SERVICE_NAME
              value: "action"
            - name: GERMAIN_XMX
              value: '2048M'
          volumeMounts:
            - name: var-logs
              mountPath: /opt/services/var
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 999
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      initContainers:
      - name: prerequisite-check
        image: busybox
        args: [
          "/bin/sh",
          "-c",
          "while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;"
        ]
        securityContext:
          privileged: true
