---
# Source: germainux/templates/infra/infra-hazelcast.yaml
apiVersion: v1
kind: Service
metadata:
  name: germainapm-hazelcast
spec:
  clusterIP: None
  selector:
    app: hazelcast
  ports:
    - name: germainapm-hazelcast-port
      port: 5701
      protocol: TCP
      targetPort: hazelcast-port
---
# Source: germainux/templates/infra/infra-hazelcast.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      volumes:
        - name: lib-path
          hostPath:
            path: /opt/hazelcast/lib
      containers:
        - image: "hazelcast/hazelcast:latest"
          imagePullPolicy: Always
          name: hazelcast
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 1000m
          ports:
            - containerPort: 5701
              name: hazelcast-port
          env:
            - name: HZ_CLUSTERNAME
              value: "germain"
          volumeMounts:
            - name: lib-path
              mountPath: /opt/hazelcast/lib/apm-rtm-model.jar
              subPath: apm-rtm-model.jar
      initContainers:
      - name: get-apm-rtm-model
        image: busybox
        command: ["/bin/sh", "-c", "wget -q https://github.com/kakinpelu/germain/raw/main/helm/germain-demo-env/config/apm-rtm-model.jar -P /opt/hazelcast/lib"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-path
          mountPath: /opt/hazelcast/lib
